# Workflow for deploying a Next.js site to GitHub Pages
name: Deploy Next.js site to Pages

on:
  # Trigger deployment when changes are pushed to the gh-pages branch
  push:
    branches:
      - gh-pages

  # Allows manual triggers for the deployment
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensures only one concurrent deployment, skipping queued runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
